### ISSUE TITLE
Running Sparse Resnet on Dense data

### ISSUE THREAD

**Issue by shurjobanerjee** [NVIDIA/MinkowskiEngine#117]
Hi, I was trying to compare the performance of the sparse resnet model to traditional dense implementations on CIFAR 10. Is this possible? My code is below (adapted from `examples/resnet.py`)

```python
def to_sparse_coo(data):
    coords, feats = [], []
    for i, row in enumerate(data):
        for j, col in enumerate(row):
            for k, val in enumerate(col):
                if val != 0:
                    coords.append([i, j, k]) 
                    feats.append([val])
    return torch.IntTensor(coords), torch.FloatTensor(feats)

class SparseCifar(torch.utils.data.Dataset):
    
    def __init__(self, dataset):
        super(SparseCifar, self).__init__()
        self.dataset = dataset

    def __getitem__(self, index):
        img, label =  self.dataset[index]
        coord, feat = to_sparse_coo(img)
        return coord, feat, label

    def __len__(self):
        return len(self.dataset)

if __name__ == '__main__':
     import torchvision.datasets as datasets

    # Initialize datasets (w/ validation set if desired)
    trainset = datasets.CIFAR10(root='./data', train=True, download=True)
    trainset = SparseCifar(trainset)
    
    # Load the "sparse" data
    dataloader = torch.utils.data.DataLoader(trainset, 
                                             batch_size=64, 
                                             shuffle=True,
                                             collate_fn=ME.utils.SparseCollation())
    criterion = nn.CrossEntropyLoss()
    net = ResNet14(in_channels=3, out_channels=10, D=3)

    # a data loader must return a tuple of coords, features, and labels.
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    net = net.to(device)
    optimizer = SGD(net.parameters(), lr=1e-2)

    for data in dataloader:
        coords, feats, labels = data
        inputs = ME.SparseTensor(feats, coords).to(device)
        outputs = net(inputs)
```
I keep getting the error: 

```
Traceback (most recent call last):
  File "mesparseresnet.py", line 218, in <module>
    outputs = net(inputs)
  File "/home/shurjo/projects/compressed-memory-incremental-learning/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "mesparseresnet.py", line 124, in forward
    x = self.conv1(x)
  File "/home/shurjo/projects/compressed-memory-incremental-learning/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shurjo/projects/compressed-memory-incremental-learning/env/lib/python3.7/site-packages/MinkowskiEngine/MinkowskiConvolution.py", line 278, in forward
    out_coords_key, input.coords_man)
  File "/home/shurjo/projects/compressed-memory-incremental-learning/env/lib/python3.7/site-packages/MinkowskiEngine/MinkowskiConvolution.py", line 61, in forward
    " does not match the kernel shape " + str(list(kernel.shape))
AssertionError: The input shape [196608, 1] does not match the kernel shape [125, 3, 64]
```

196608 is equal to the batch size times the dimensions of the CIFAR data - not sure why the sparse matrix is interpreted as a row vector though?

I was wondering if anyone could help me debug what I'm doing wrong here.

**Comment by wecacuee** [comment]
I tried to reproduce your script but I need cifar_train module for that.

**Comment by shurjobanerjee** [comment]
I edited the script to not require cifar_train anymore. The dataset is loaded through the `torchvision` module.

**Comment by wecacuee** [comment]
`feats` must of shape `(N, nchannel)`. Since your `feats` has shape  `(196608, 1)`, but your `Resnet14` accepts `in_channels=3`, hence this error. 

Changing `in_channels=1` fixes the error.
