### ISSUE TITLE
Installation of MinkowskiEngine on HPC cluster

### ISSUE THREAD

**Issue by samfux84** [NVIDIA/MinkowskiEngine#182]
Hi,

I already asked some questions regarding the MinkowskiEngine installation in a previous issue (https://github.com/NVIDIA/MinkowskiEngine/issues/94) where you provided some help.

Due to a operating system upgrade that broke the installation I removed the existing installation and I am now trying again to install MinkowskiEngine.

But no matter what I try to do (pip installation, installation with python setup.py install) I always get an error message regarding the hipcc compiler missing:

```
[sfux@lo-login-01 ~]$ bsub -Is -n 1 -W 3:00 -R "rusage[mem=4096, ngpus_excl_p=1]" bash                                                                                                                         Generic job.
Job <7000500> is submitted to queue <gpu.4h>.
<<Waiting for dispatch ...>>
<<Starting on lo-s4-034>>
[sfux@lo-s4-034 ~]$ module list

Currently Loaded Modules:
  1) StdEnv   2) gcc/4.8.5

[sfux@lo-s4-034 ~]$ module load gcc/6.3.0 python_gpu/3.7.4

The following have been reloaded with a version change:
  1) gcc/4.8.5 => gcc/6.3.0

[sfux@lo-s4-034 ~]$ module load eth_proxy
[sfux@lo-s4-034 ~]$ pip install git+https://github.com/StanfordVL/MinkowskiEngine --install-option="--force_cuda" --install-option="--cuda_home=/cluster/apps/gcc-6.3.0/cuda-10.1.243-n6qg6z5js3zfnhp2cfg5yjccej636czm" --install-option="--blas=openblas" --install-option="--blas_include_dirs=/cluster/apps/gcc-6.3.0/openblas-0.2.19-jusdys62qhv52qjbsoewvthriekuaynw/include" --install-option="--blas_library_dirs=/cluster/apps/gcc-6.3.0/openblas-0.2.19-jusdys62qhv52qjbsoewvthriekuaynw/lib"
/cluster/apps/python/3.7.4_gpu_gcc630/x86_64/lib64/python3.7/site-packages/pip/_internal/commands/install.py:244: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Collecting git+https://github.com/StanfordVL/MinkowskiEngine
  Cloning https://github.com/StanfordVL/MinkowskiEngine to /scratch/7000500.tmpdir/pip-req-build-wepmvacm
  Running command git clone -q https://github.com/StanfordVL/MinkowskiEngine /scratch/7000500.tmpdir/pip-req-build-wepmvacm
    ERROR: Command errored out with exit status 1:
     command: /cluster/apps/python/3.7.4_gpu_gcc630/x86_64/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/scratch/7000500.tmpdir/pip-req-build-wepmvacm/setup.py'"'"'; __file__='"'"'/scratch/7000500.tmpdir/pip-req-build-wepmvacm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /scratch/7000500.tmpdir/pip-req-build-wepmvacm/pip-egg-info
         cwd: /scratch/7000500.tmpdir/pip-req-build-wepmvacm/
    Complete output (9 lines):
    which: no hipcc in (/cluster/apps/gcc-6.3.0/libpng-1.6.27-7vevbsio2diw5xquq7oxg7fphkppf2kx/bin:/cluster/apps/gcc-6.3.0/jpeg-9b-742nyforj7mfuhcfzbsbqjlmiya2wi5e/bin:/cluster/apps/gcc-6.3.0/cuda-10.1.243-n6qg6z5js3zfnhp2cfg5yjccej636czm/bin:/cluster/apps/gcc-6.3.0/openblas-0.2.19-jusdys62qhv52qjbsoewvthriekuaynw/bin:/cluster/apps/python/3.7.4_gpu_gcc630/x86_64/bin:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/gcc-6.3.0-d7fey5ouwb3cw26w5zqafqcse7q3fs6d/bin:/cluster/home/sfux/spacktest/spack/bin:/cluster/apps/lsf/10.1/linux3.10-glibc2.17-x86_64/bin:/cluster/apps/lsf/10.1/linux3.10-glibc2.17-x86_64/bin:/cluster/home/sfux/spacktest/spack/bin:/cluster/apps/local:/cluster/apps/sfos/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/cluster/home/sfux/.local/bin:/cluster/home/sfux/bin:/cluster/apps/adm:/cluster/home/sfux/bin)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/scratch/7000500.tmpdir/pip-req-build-wepmvacm/setup.py", line 175, in <module>
        \nfor more information, please visit https://github.com/NVIDIA/MinkowskiEngine/wiki/Installation'
    ImportError:
    BLAS not found from numpy.distutils.system_info.get_info.
    Please specify BLAS with: python setup.py install --blas=openblas"
    for more information, please visit https://github.com/NVIDIA/MinkowskiEngine/wiki/Installation
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
[sfux@lo-s4-034 ~]$
```

Is this a known issue? Is the hipcc compiler required to install MinkowskiEngine?

Best regards

Sam

**Comment by samfux84** [comment]
Some additional information:

I am using pytorch 1.5.1 installed with the command:

pip install torch==1.5.1+cu101 torchvision==0.6.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html

It looks like the the hipcc message is coming from pytorch, but I think that pytorch 1.5.1 should be supported by MinkowskiEngine:

```
[sfux@lo-login-01 ~]$ bsub -Is -n 1 -W 1:00 -R "rusage[mem=4096, ngpus_excl_p=1]" bash
Generic job.
Job <7000700> is submitted to queue <gpu.4h>.
<<Waiting for dispatch ...>>
<<Starting on lo-s4-010>>
[sfux@lo-s4-010 ~]$ module load gcc/6.3.0 python_gpu/3.7.4 eth_proxy

The following have been reloaded with a version change:
  1) gcc/4.8.5 => gcc/6.3.0

[sfux@lo-s4-010 ~]$ python
Python 3.7.4 (default, Oct 17 2019, 10:45:10)
[GCC 6.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from torch.utils.cpp_extension import _find_cuda_home; print(_find_cuda_home())
which: no hipcc in (/cluster/apps/gcc-6.3.0/libpng-1.6.27-7vevbsio2diw5xquq7oxg7fphkppf2kx/bin:/cluster/apps/gcc-6.3.0/jpeg-9b-742nyforj7mfuhcfzbsbqjlmiya2wi5e/bin:/cluster/apps/gcc-6.3.0/cuda-10.1.243-n6qg6z5js3zfnhp2cfg5yjccej636czm/bin:/cluster/apps/gcc-6.3.0/openblas-0.2.19-jusdys62qhv52qjbsoewvthriekuaynw/bin:/cluster/apps/python/3.7.4_gpu_gcc630/x86_64/bin:/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/gcc-6.3.0-d7fey5ouwb3cw26w5zqafqcse7q3fs6d/bin:/cluster/home/sfux/spacktest/spack/bin:/cluster/apps/lsf/10.1/linux3.10-glibc2.17-x86_64/bin:/cluster/apps/lsf/10.1/linux3.10-glibc2.17-x86_64/bin:/cluster/home/sfux/spacktest/spack/bin:/cluster/apps/local:/cluster/apps/sfos/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/cluster/home/sfux/.local/bin:/cluster/home/sfux/bin:/cluster/apps/adm:/cluster/home/sfux/bin)
/cluster/apps/gcc-6.3.0/cuda-10.1.243-n6qg6z5js3zfnhp2cfg5yjccej636czm
>>>
```

I will remove this part from the Makefile, set the $CUDA_HOME directly instead of querying it through torch and try again the installation with python setup.py install.

**Comment by samfux84** [comment]
In order to fix the problem with the torch calls I was running them in directly in Python and replaced them in setup.py and Makefile by the result without the warning from pytorch.

Now things look a bit better but now I am getting compilation errors:

```
Using BLAS=openblas
CXX src/pooling_global_max.cpp
CXX src/region.cpp
CXX src/convolution_transpose.cpp
CXX src/coordsmap.cpp
CXX src/coords_manager.cpp
CXX src/broadcast.cpp
CXX src/quantization.cpp
CXX src/pooling_avg.cpp
CXX src/math_functions.cpp
CXX src/pooling_global_avg.cpp
CXX src/union.cpp
CXX src/pooling_transpose.cpp
src/coordsmap.cpp: In member function ‘minkowski::InOutMapsPair<int> minkowski::CoordsMap<MapType>::kernel_map(const minkowski::CoordsMap<robin_hood::detail::Table<true, 80ul, std::vector<int>, int, minkowski::byte_hash_vec<int>, std::equal_to<std::vector<int> > > >&, const minkowski::Region&) const’:
src/coordsmap.cpp:516:11: error: ‘#pragma omp atomic capture’ uses two different expressions for memory
           }
           ^
src/coordsmap.cpp:549:13: error: ‘#pragma omp atomic capture’ uses two different expressions for memory
             }
             ^
CXX src/coords_key.cpp
Makefile:133: recipe for target 'objs/coordsmap.o' failed
make: *** [objs/coordsmap.o] Error 1
make: *** Waiting for unfinished jobs....
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
```

Is this a known problem? And do you have any advise on how to fix this?

**Comment by samfux84** [comment]
Changed back from master branch to version 0.4.2. With the replacement of the torch commands in setup.py and Makefile the installation worked.

**Comment by janardhan08** [comment]
> Changed back from master branch to version 0.4.2. With the replacement of the torch commands in setup.py and Makefile the installation worked.

@samfux84 how did you slove this issue

**Comment by samfux84** [comment]
Checkout the version 0.4.2. Then have a look at the setup.py file. There are some torch commands. Copy them and run them in a Python interpreter on your system (using the Python version for which you would like to install MinkowskiEngine). They should give the same warning about hipcc. Then copy everything (except the warning) and use it to replace the torch command in setup.py. In my case this worked

**Comment by janardhan08** [comment]
@samfux84 I tried your approach but still. i get the same error.

**Comment by samfux84** [comment]
Do you still get the warnings about hipcc, or the error "error: ‘#pragma omp atomic capture’ uses two different expressions for memory"?

**Comment by janardhan08** [comment]
@samfux84 Now I am getting this error.

NVCC src/pooling_max.cu
nvcc fatal   : Value 'c++14' is not defined for option 'std'
Makefile:166: recipe for target 'objs/cuda/pooling_max.o' failed
make: *** [objs/cuda/pooling_max.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** wait: No child processes.  Stop.
Traceback (most recent call last):
  File "setup.py", line 146, in <module>
    run_command(*compile_args)
  File "setup.py", line 48, in run_command
    subprocess.check_call(args)
  File "/Data4T/janardhan/anaconda3/envs/py3-mink-2/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-j12', 'PYTHON=/Data4T/janardhan/anaconda3/envs/py3-mink-2/bin/python', 'BLAS=openblas')' returned non-zero exit status 2

**Comment by samfux84** [comment]
Please check https://github.com/pytorch/pytorch/issues/32135

**Comment by janardhan08** [comment]
> Please check [pytorch/pytorch#32135](https://github.com/pytorch/pytorch/issues/32135)

@samfux84 It still shows me the same error, Not sure whats happening

**Comment by janardhan08** [comment]
@samfux84 my problem is solved. I had multiple cuda versions installed in our server. so that is why it didn't work. Thank you for your help.

**Comment by SBXGary** [comment]
> @samfux84 my problem is solved. I had multiple cuda versions installed in our server. so that is why it didn't work. Thank you for your help.

Hi, how do you fix the problem with multiple CUDAs? Are there any CUDA Settings we should pay attention to?

**Comment by chrischoy** [comment]
When you have multiple cuda versions, use the environment variable `CUDA_HOME`.

```
# setup.py
export CUDA_HOME=/usr/local/cuda-11.1; python setup.py install
# pip
export CUDA_HOME=/usr/local/cuda-11.1; pip install MinkowskiEngine
```
