### ISSUE TITLE
trying to install on windows WSL with CPU ONLY

### ISSUE THREAD

**Issue by maorp** [NVIDIA/MinkowskiEngine#215]
Hey. I get the following error when trying to install on windows WSL with CPU ONLY - 
--------------------------------
| WARNING: CPU_ONLY build set  |
--------------------------------

Using BLAS=mkl
CXX src/region.cpp
CXX src/coordsmap.cpp
CXX src/pooling_max.cpp
CXX src/pooling_transpose.cpp
make: g++: Command not found
make: g++: Command not found
make: g++: Command not found
make: g++: Command not found
make: *** [Makefile:163: objs/region.o] Error 127
make: *** Waiting for unfinished jobs....
make: *** [Makefile:163: objs/coordsmap.o] Error 127
make: *** [Makefile:163: objs/pooling_max.o] Error 127
make: *** [Makefile:163: objs/pooling_transpose.o] Error 127
Traceback (most recent call last):
  File "setup.py", line 188, in <module>
    run_command(*compile_args)
  File "setup.py", line 90, in run_command
    subprocess.check_call(args)
  File "/home/maorp/anaconda3/envs/py3-fcgf/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-j12', 'PYTHON=/home/maorp/anaconda3/envs/py3-fcgf/bin/python', 'CPU_ONLY=1', 'BLAS=mkl')' returned non-zero exit status 2.

**Comment by samanemami** [comment]
I have the same issue!
