### ISSUE TITLE
RuntimeError:  invalid device function at src/convolution.cu:283

### ISSUE THREAD

**Issue by Violetit** [NVIDIA/MinkowskiEngine#221]
Hi, @drossetti 
Thanks for sharing the wonderful project!
Could please help me with the below error, it occurs when I run the script `indoor.py` in examples.

Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/mink/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/.conda/envs/mink/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/disk/tia/MinkowskiEngine/examples/unet.py", line 121, in <module>
    output = net(input)
  File "/home/ubuntu/.conda/envs/mink/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/disk/tia/MinkowskiEngine/examples/unet.py", line 90, in forward
    out_s1 = self.block1(x)
  File "/home/ubuntu/.conda/envs/mink/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/.conda/envs/mink/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/ubuntu/.conda/envs/mink/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/disk/tia/MinkowskiEngine/MinkowskiEngine/MinkowskiConvolution.py", line 281, in forward
    input.coords_man)
  File "/disk/tia/MinkowskiEngine/MinkowskiEngine/MinkowskiConvolution.py", line 92, in forward
    ctx.coords_man.CPPCoordsManager)
RuntimeError:  invalid device function at src/convolution.cu:283
Segmentation fault (core dumped)

**Comment by xmyqsh** [comment]
Try to reinstall it by `force cuda`:
```
python setup.py install --force_cuda --cuda_home=/usr/local/cuda
```

**Comment by chrischoy** [comment]
It seems that your GPU might not compatible.

What GPU are you using?

**Comment by Violetit** [comment]
> It seems that your GPU might not compatible.
> The MinkowskiEngine requires minimum Kepler arch GPUs.
> 
> What GPU are you using?

**Comment by Violetit** [comment]
> It seems that your GPU might not compatible.
> The MinkowskiEngine requires minimum Kepler arch GPUs.
> 
> What GPU are you using?

I use the Titan RTX GPU. 
I reinstall the CUDA with version 10.2,  it seems right now.
I am testing it on FCGF, and catch  an error 
https://github.com/chrischoy/FCGF/issues/38[(https://github.com/chrischoy/FCGF/issues/38)]
