### ISSUE TITLE
0.50 error with new Sparse Tensor generation

### ISSUE THREAD

**Issue by aniqueakhtar** [NVIDIA/MinkowskiEngine#240]
I used to do this in the past:
```
y3 = ME.SparseTensor(f2, coords_key=y.coords_key, coords_manager=y.coords_man).to(device)
```

Now if I try this:
```
y3 = ME.SparseTensor(f2, coordinate_map_key=y.coordinate_map_key, coordinate_manager=y.coordinate_manager, device=device)
```
I get this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anique/anaconda3/envs/mink2/lib/python3.7/site-packages/MinkowskiEngine/MinkowskiTensor.py", line 267, in __init__
    coordinates = coordinates.to(device)
AttributeError: 'NoneType' object has no attribute 'to'
```

**Comment by chrischoy** [comment]
Thanks for the issue. I'll post the fix soon.
