### ISSUE TITLE
ResNet fails when batch_size=1

### ISSUE THREAD

**Issue by maxjaritz** [NVIDIA/MinkowskiEngine#291]
**Describe the bug**
The `resnets.py` example fails with `batch_size=1` throwing the following error:
```
Traceback (most recent call last):
  File "/home/ubuntu/MinkowskiEngine/examples/resnet.py", line 242, in <module>
    output = net(input)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/MinkowskiEngine/examples/resnet.py", line 129, in forward
    x = self.layer1(x)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/MinkowskiEngine/MinkowskiEngine/modules/resnet_block.py", line 56, in forward
    out = self.norm1(out)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/MinkowskiEngine/MinkowskiEngine/MinkowskiNormalization.py", line 75, in forward
    output = self.bn(input.F)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/torch/nn/functional.py", line 2054, in batch_norm
    _verify_batch_size(input.size())
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/torch/nn/functional.py", line 2037, in _verify_batch_size
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 64])

Process finished with exit code 1
```

**To Reproduce**
Change the following line:
https://github.com/NVIDIA/MinkowskiEngine/blob/ada7f737e1a01365124d2ec8b2c9138882ac9670/examples/resnet.py#L237

to
```
coords, feat, label = data_loader(batch_size=1)
```

**Expected behavior**
The example should run without errors.

**Desktop (please complete the following information):**

 - OS: Ubuntu 18.04
 - CUDA version: 10.2
 - NVIDIA Driver version: 450.80.02
 - Minkowski Engine version 0.5.0
 - Please paste the output of the following command
```
==========System==========
Linux-5.4.0-1034-aws-x86_64-with-debian-buster-sid
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
==========Pytorch==========
1.7.1
torch.cuda.is_available(): True
==========NVIDIA-SMI==========
/usr/bin/nvidia-smi
Driver Version 450.80.02
CUDA Version 11.0
VBIOS Version 88.00.4F.00.09
Image Version G503.0201.00.03
==========NVCC==========
/usr/local/cuda/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
==========CC==========
/usr/bin/c++
c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

==========MinkowskiEngine==========
0.5.0
MinkowskiEngine compiled with CUDA Support: True
NVCC version MinkowskiEngine is compiled: 10020
```
**Additional context**
Initially, I wanted to run testing on my custom dataset with `batch_size=1` and encountered the following error:
```
resnet.py", line 134, in forward
    x = self.glob_pool(x)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/MinkowskiEngine/MinkowskiPooling.py", line 673, in forward
    coordinate_manager=input.coordinate_manager,
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/MinkowskiEngine/MinkowskiSparseTensor.py", line 194, in __init__
    ), f"The feature should be a matrix, The input feature is an order-{features.ndim} tensor."
AssertionError: The feature should be a matrix, The input feature is an order-1 tensor.
```

**Comment by chrischoy** [comment]
The first error is a user error due to the batch normalization.

```
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 64])
```

To train batch normalization, which computes standard deviation of a batch, you need to provide batch_size>1.

The second error will be fixed in the next commit.

**Comment by maxjaritz** [comment]
Thanks for the fast fix!!!
