### ISSUE TITLE
Cannot import Minkowski Engine

### ISSUE THREAD

**Issue by Xinghui-Li** [NVIDIA/MinkowskiEngine#305]
**Describe the bug**
Cannot import Minkowski Engine

Traceback (most recent call last):
  File "playground.py", line 174, in <module>
    import MinkowskiEngine as ME
  File "/home/xinghui/miniconda3/envs/mink/lib/python3.7/site-packages/MinkowskiEngine/__init__.py", line 53, in <module>
    from MinkowskiEngineBackend._C import (
ImportError: /home/xinghui/miniconda3/envs/mink/lib/python3.7/site-packages/MinkowskiEngineBackend/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE

**To Reproduce**
import MinkowskiEngine as ME

**Expected behavior**
It should import the library

**Desktop (please complete the following information):**

 - OS: Ubuntu 18.04
 - Python version: 3.7.9
 - CUDA version: 10.2
 - NVIDIA Driver version: 440.33.01
 - Minkowski Engine version 0.5.0
 - Output of the following command. (If you installed the latest MinkowskiEngine, simply call `MinkowskiEngine.print_diagnostics()`)

```
wget -q https://raw.githubusercontent.com/NVIDIA/MinkowskiEngine/master/MinkowskiEngine/diagnostics.py ; python diagnostics.py
```

**Additional context**
I believe the installation requirement should be updated since I found out that v0.5.0 only support pytorch>=1.7. This could cause by compatibility with other things. What's more, I got this error by updating ME from v0.43 to v0.5 by anaconda by running the installation code:
pip install -U git+https://github.com/NVIDIA/MinkowskiEngine -v --no-deps --install-option="--blas_include_dirs=${CONDA_PREFIX}/include" --install-option="--blas=openblas"

**Comment by Xinghui-Li** [comment]
Solve the problem by reinstalling the entire environment.
