### ISSUE TITLE
AttributeError: 'SparseTensor' object has no attribute 'log_softmax'

### ISSUE THREAD

**Issue by djlbet123** [NVIDIA/MinkowskiEngine#309]
Environment :
    Ubuntu 20.04 LTS
    GTX 1650
    CUDA == 11.1
    torch == 1.7.1
    MinkowskiEngine == 0.5.0

Code :
    criterion = torch.nn.CrossEntropyLoss()
    for batch_id, data in tqdm(enumerate(trainDataLoader, 0), total=len(trainDataLoader), smoothing=0.9):
                points, feats, target = data
                points = ME.SparseTensor(feats, points, device = 'cuda')
                target = target.cuda()
                optimizer.zero_grad()
                classifier = classifier.train()
                pred = classifier(points)     # The last layer is  MinkowskiEngine.MinkowskiLinear(in_channels, out_channels)
                loss = criterion(pred, target.long())

Error report :
    Traceback (most recent call last):
      File "train_cls.py", line 213, in <module>
        main(args)
      File "train_cls.py", line 171, in main
        loss = criterion(pred, target.long())
      File "/home/summerriver/anaconda3/envs/point/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
        result = self.forward(*input, **kwargs)
      File "/home/summerriver/anaconda3/envs/point/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 961, in forward
        return F.cross_entropy(input, target, weight=self.weight,
      File "/home/summerriver/anaconda3/envs/point/lib/python3.8/site-packages/torch/nn/functional.py", line 2468, in cross_entropy
        return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
      File "/home/summerriver/anaconda3/envs/point/lib/python3.8/site-packages/torch/nn/functional.py", line 1605, in log_softmax
        ret = input.log_softmax(dim)
    AttributeError: 'SparseTensor' object has no attribute 'log_softmax'

How should I do?

**Comment by chrischoy** [comment]
You are mixing the pytorch function with MinkowskiEngine sparse tensors directly.
Please refer to the classification example in https://github.com/NVIDIA/MinkowskiEngine/blob/master/examples/modelnet40.py to do this correctly.

**Comment by djlbet123** [comment]
Thanks, it seems that applying ''loss = criterion(pred.F, target.long())''  is useful.
