### ISSUE TITLE
Outdated code in examples/reconstruction.py

### ISSUE THREAD

**Issue by P-Light** [NVIDIA/MinkowskiEngine#323]
Hello! Trying execute:
```
python -m examples.reconstruction --eval
```

Output:
```
Traceback (most recent call last):
  File "/home/plight/anaconda3/envs/minkowski/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/plight/anaconda3/envs/minkowski/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/plight/workspace/rand-MinkowskiEngine-docker/MinkowskiEngine/examples/reconstruction.py", line 619, in <module>
    visualize(net, dataloader, device, config)
  File "/home/plight/workspace/rand-MinkowskiEngine-docker/MinkowskiEngine/examples/reconstruction.py", line 544, in visualize
    sin = ME.SparseTensor(
TypeError: __init__() got an unexpected keyword argument 'feats'
```

It seems 
```
sin = ME.SparseTensor(
            feats=in_feat,
            coords=init_coords,
            allow_duplicate_coords=True,  # for classification, it doesn't matter
            tensor_stride=config.resolution,
        ).to(device)
```
has outdated, because must be features instead of feats, coordinates instead of coords. Also allow_duplicate_coords not in ME.SparseTensor constructor, method "to" not found. 

UPD: found that similar code is in train function:
```
sin = ME.SparseTensor(
features=in_feat,
coordinates=init_coords,
tensor_stride=config.resolution,
device=device,
)

# Generate target sparse tensor
cm = sin.coordinate_manager
target_key, _ = cm.insert_and_map(
ME.utils.batched_coordinates(data_dict["xyzs"]).to(device),
string_id="target",
)
```
after replacing:
```
Traceback (most recent call last):
  File "/home/plight/anaconda3/envs/minkowski/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/plight/anaconda3/envs/minkowski/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/plight/workspace/rand-MinkowskiEngine-docker/MinkowskiEngine/examples/reconstruction.py", line 633, in <module>
    visualize(net, dataloader, device, config)
  File "/home/plight/workspace/rand-MinkowskiEngine-docker/MinkowskiEngine/examples/reconstruction.py", line 584, in visualize
    pcd = PointCloud(coords)
  File "/home/plight/workspace/rand-MinkowskiEngine-docker/MinkowskiEngine/examples/reconstruction.py", line 74, in PointCloud
    pcd.points = o3d.utility.Vector3dVector(points)
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

**Comment by P-Light** [comment]
It seems code updating hasn't resolved described issue. I have all the bugs documented up to [8695696] (https://github.com/NVIDIA/MinkowskiEngine/commit/8695696aa0d7bf1c0def0d1e1c9fe544ac71f64d), including changing the code myself.
