### ISSUE TITLE
Pytorch 1.8 Installation Error

### ISSUE THREAD

**Issue by abahnasy** [NVIDIA/MinkowskiEngine#324]
I'm facing this error during installation of the lastest tag, could you please advise?

```
error: Command "/usr/local/cuda-11.1/bin/nvcc -I/home/ubuntu/.local/lib/python3.6/site-packages/torch/include -I/home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/ubuntu/.local/lib/python3.6/site-packages/torch/include/TH -I/home/ubuntu/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-11.1/include -I/tmp/pip-install-h0qf4c1j/minkowskiengine_cbe6c9f1431c448ebb025933425c6335/src -I/tmp/pip-install-h0qf4c1j/minkowskiengine_cbe6c9f1431c448ebb025933425c6335/src/3rdparty -I/usr/include/python3.6m -c /tmp/pip-install-h0qf4c1j/minkowskiengine_cbe6c9f1431c448ebb025933425c6335/src/quantization.cpp -o build/temp.linux-x86_64-3.6/tmp/pip-install-h0qf4c1j/minkowskiengine_cbe6c9f1431c448ebb025933425c6335/src/quantization.o -fopenmp -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14" failed with exit status 1
    Running setup.py install for MinkowskiEngine ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-h0qf4c1j/minkowskiengine_cbe6c9f1431c448ebb025933425c6335/setup.py'"'"'; __file__='"'"'/tmp/pip-install-h0qf4c1j/minkowskiengine_cbe6c9f1431c448ebb025933425c6335/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-i7213ci3/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/ubuntu/.local/include/python3.6m/MinkowskiEngine Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 826, in install
    req_description=str(self.req),
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/install/legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 400, in run
    pycompile=options.compile,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/__init__.py", line 88, in install_given_reqs
    pycompile=pycompile,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 830, in install
    six.reraise(*exc.parent)
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/install/legacy.py", line 76, in install
    cwd=unpacked_source_directory,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/subprocess.py", line 293, in runner
    spinner=spinner,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/subprocess.py", line 258, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-h0qf4c1j/minkowskiengine_cbe6c9f1431c448ebb025933425c6335/setup.py'"'"'; __file__='"'"'/tmp/pip-install-h0qf4c1j/minkowskiengine_cbe6c9f1431c448ebb025933425c6335/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-i7213ci3/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/ubuntu/.local/include/python3.6m/MinkowskiEngine Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-61946whv'
```

Environment Details:
```
==========System==========
Linux-5.4.0-1038-aws-x86_64-with-Ubuntu-18.04-bionic
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
3.6.9 (default, Jan 26 2021, 15:33:00)
[GCC 8.4.0]
==========Pytorch==========
1.8.0
torch.cuda.is_available(): True
==========NVIDIA-SMI==========
/usr/bin/nvidia-smi
Driver Version 450.80.02
CUDA Version 11.0
VBIOS Version 90.04.84.00.06
Image Version G183.0200.00.02
==========NVCC==========
/usr/local/cuda/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
==========CC==========
/usr/bin/c++
c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

==========MinkowskiEngine==========
MinkowskiEngine not installed
```

**Comment by abahnasy** [comment]
Follow up, after updating to CUDA 11.2

```
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/ubuntu/.local/lib/python3.6/site-packages/torch/include -I/home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/ubuntu/.local/lib/python3.6/site-packages/torch/include/TH -I/home/ubuntu/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/tmp/pip-install-ngtnouzd/minkowskiengine_83d795ae506945adb508a3e9c209ab5d/src -I/tmp/pip-install-ngtnouzd/minkowskiengine_83d795ae506945adb508a3e9c209ab5d/src/3rdparty -I/usr/include/python3.6m -c /tmp/pip-install-ngtnouzd/minkowskiengine_83d795ae506945adb508a3e9c209ab5d/src/direct_max_pool.cpp -o build/temp.linux-x86_64-3.6/tmp/pip-install-ngtnouzd/minkowskiengine_83d795ae506945adb508a3e9c209ab5d/src/direct_max_pool.o -fopenmp -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    In file included from /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/ATen/ATen.h:13:0,
                     from /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                     from /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                     from /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                     from /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                     from /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                     from /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                     from /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                     from /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                     from /tmp/pip-install-ngtnouzd/minkowskiengine_83d795ae506945adb508a3e9c209ab5d/src/direct_max_pool.cpp:30:
    /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/ATen/Dispatch.h: In function ‘constexpr bool at::should_include_kernel_dtype(const char*, c10::ScalarType)’:
    /home/ubuntu/.local/lib/python3.6/site-packages/torch/include/ATen/Dispatch.h:24:23: error: redefinition of ‘constexpr bool at::should_include_kernel_dtype(const char*, c10::ScalarType)’
     inline constexpr bool should_include_kernel_dtype(
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from /tmp/pip-install-ngtnouzd/minkowskiengine_83d795ae506945adb508a3e9c209ab5d/src/direct_max_pool.cpp:27:0:
    /tmp/pip-install-ngtnouzd/minkowskiengine_83d795ae506945adb508a3e9c209ab5d/src/dispatcher.hpp:24:23: note: ‘constexpr bool at::should_include_kernel_dtype(const char*, c10::ScalarType)’ previously defined here
     inline constexpr bool should_include_kernel_dtype(const char *kernel_tag_str,
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Running setup.py install for MinkowskiEngine ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ngtnouzd/minkowskiengine_83d795ae506945adb508a3e9c209ab5d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ngtnouzd/minkowskiengine_83d795ae506945adb508a3e9c209ab5d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-u2xguwgu/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/ubuntu/.local/include/python3.6m/MinkowskiEngine --blas=openblas Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 826, in install
    req_description=str(self.req),
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/install/legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 400, in run
    pycompile=options.compile,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/__init__.py", line 88, in install_given_reqs
    pycompile=pycompile,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 830, in install
    six.reraise(*exc.parent)
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/install/legacy.py", line 76, in install
    cwd=unpacked_source_directory,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/subprocess.py", line 293, in runner
    spinner=spinner,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/subprocess.py", line 258, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ngtnouzd/minkowskiengine_83d795ae506945adb508a3e9c209ab5d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ngtnouzd/minkowskiengine_83d795ae506945adb508a3e9c209ab5d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-u2xguwgu/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/ubuntu/.local/include/python3.6m/MinkowskiEngine --blas=openblas Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-8ycootd9'
```

Environment Details:
```
==========System==========
Linux-5.4.0-1038-aws-x86_64-with-Ubuntu-18.04-bionic
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
3.6.9 (default, Jan 26 2021, 15:33:00)
[GCC 8.4.0]
==========Pytorch==========
1.8.0
torch.cuda.is_available(): True
==========NVIDIA-SMI==========
/usr/bin/nvidia-smi
Driver Version 460.32.03
CUDA Version 11.2
VBIOS Version 90.04.84.00.06
Image Version G183.0200.00.02
==========NVCC==========
/usr/local/cuda/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Jan_28_19:32:09_PST_2021
Cuda compilation tools, release 11.2, V11.2.142
Build cuda_11.2.r11.2/compiler.29558016_0
==========CC==========
/usr/bin/c++
c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

==========MinkowskiEngine==========
MinkowskiEngine not installed
```

**Comment by chrischoy** [comment]
Please use pytorch 1.7.1.

**Comment by abahnasy** [comment]
Working now with Pytroch 1.7.1. Thank you
