### ISSUE TITLE
ME v0.4.3 install error

### ISSUE THREAD

**Issue by ishanic** [NVIDIA/MinkowskiEngine#326]
I checked out and built v0.4.3. The compilation went through, but when importing the module inside Python I receive this following error. Please see the diagnostics output below. 
```
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import MinkowskiEngine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/pc_env/lib/python3.7/site-packages/MinkowskiEngine-0.4.3-py3.7-linux-x86_64.egg/MinkowskiEngine/__init__.py", line 36, in <module>
    from MinkowskiEngineBackend import MemoryManagerBackend
ImportError: /home/user/miniconda3/envs/pc_env/lib/python3.7/site-packages/MinkowskiEngine-0.4.3-py3.7-linux-x86_64.egg/MinkowskiEngineBackend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cusparseDcsrmm2
```

```
==========System==========
Linux-4.15.0-122-generic-x86_64-with-debian-buster-sid
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0]
==========Pytorch==========
1.7.1
torch.cuda.is_available(): True
==========NVIDIA-SMI==========
/usr/bin/nvidia-smi
Driver Version 460.32.03
CUDA Version 11.2
VBIOS Version 90.02.2E.00.0C
Image Version G001.0000.02.04
==========NVCC==========
/usr/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
==========CC==========
/usr/bin/c++
c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

==========MinkowskiEngine==========
MinkowskiEngine not installed
```

**Comment by r-dh** [comment]
I faced the same issue, with almost identical diagnostic output after switching from torch 1.8.0 to 1.7.1

CUDA 11.2 didn't do it for me, I got an error concerning `compute_30`.

Support for which has been removed since CUDA 10.2, so what made it work was adding `export CUDA_HOME=/usr/local/cuda-10.1;` to the installation command.

**Comment by ishanic** [comment]
Going to CUDA 10.2 did actually work. Thanks, @r-dh!
