### ISSUE TITLE
MemoryError: std::bad_alloc: temporary_buffer::allocate: get_temporary_buffer failed

### ISSUE THREAD

**Issue by chalth** [NVIDIA/MinkowskiEngine#331]
Hi,when i run the code,i meet with the follow question:

  File "train.py", line 76, in <module>
    main(config)
  File "train.py", line 55, in main
    trainer.train()
  File "/home/lthach/DeepGlobalRegistration/core/trainer.py", line 135, in train
    self._train_epoch(epoch)
  File "/home/lthach/DeepGlobalRegistration/core/trainer.py", line 219, in _train_epoch
    reg_soutput = self.inlier_model(reg_sinput)
  File "/home/lthach/anaconda3/envs/py3-mink/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lthach/DeepGlobalRegistration/model/resunet.py", line 153, in forward
    out_s1 = self.conv1(x)
  File "/home/lthach/anaconda3/envs/py3-mink/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lthach/anaconda3/envs/py3-mink/lib/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiConvolution.py", line 321, in forward
    input._manager,
  File "/home/lthach/anaconda3/envs/py3-mink/lib/python3.6/site-packages/MinkowskiEngine-0.5.2-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiConvolution.py", line 84, in forward
    coordinate_manager._manager,
MemoryError: std::bad_alloc: temporary_buffer::allocate: get_temporary_buffer failed
Namespace(adam_beta1=0.9, adam_beta2=0.999, batch_size=4, best_val_metric='succ_rate', bn_momentum=0.05, clip_weight_thresh=0.05, dataset='ThreeDMatchPairDataset03', dist_type='L2', eval_registration=True, exp_gamma=0.99, fast_validation=False, feat_conv1_kernel_size=3, feat_model='SimpleNetBN2C', feat_model_n_out=16, hit_ratio_thresh=0.1, icp_cache_path='icp', inlier_conv1_kernel_size=3, inlier_direct_loss_weight=1.0, inlier_feature_type='ones', inlier_knn=1, inlier_model='ResUNetBN2C', inlier_use_direct_loss=True, iter_size=1, kitti_date='2011_09_26', kitti_dir=None, kitti_max_time_diff=3, knn_search_method='gpu', lr=0.1, max_epoch=100, max_scale=1.2, min_scale=0.8, momentum=0.8, nn_max_n=250, normalize_feature=True, num_train_iter=-1, optimizer='SGD', out_dir='outputs', pcd0='redkitchen_000.ply', pcd1='redkitchen_010.ply', positive_pair_search_voxel_size_multiplier=1.5, procrustes_loss_weight=1.0, resume=None, resume_dir=None, rotation_range=360, save_epoch_freq=1, scheduler='ExpLR', sgd_dampening=0.1, sgd_momentum=0.9, stat_freq=40, success_rre_thresh=15, success_rte_thresh=0.3, test_num_workers=0, test_phase='test', test_random_crop=False, test_random_rotation=False, test_valid=True, threed_match_dir='/home/lthach/DeepGlobalRegistration/data/threedmatch', train_num_workers=0, train_phase='train', trainer='WeightedProcrustesTrainer', trans_weight=1, use_balanced_loss=False, use_gpu=True, use_random_rotation=True, use_random_scale=False, use_xyz_feature=False, val_batch_size=1, val_epoch_freq=1, val_max_iter=400, val_num_workers=0, val_phase='val', voxel_size=0.025, weight_decay=0.0001, weights='./outputs/Experiment2/ThreeDMatchPairDataset03-v0.05/ResUNetBNF/SGD-lr1e-1-e100-b8i1-modelnout32/2021-03-14_17-00-09/best_val_checkpoint.pth', weights_dir=None)
=> loading checkpoint './outputs/Experiment2/ThreeDMatchPairDataset03-v0.05/ResUNetBNF/SGD-lr1e-1-e100-b8i1-modelnout32/2021-03-14_17-00-09/best_val_checkpoint.pth'
Traceback (most recent call last):
  File "/home/lthach/anaconda3/envs/py3-mink/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lthach/anaconda3/envs/py3-mink/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lthach/DeepGlobalRegistration/scripts/test_3dmatch.py", line 163, in <module>
    dgr = DeepGlobalRegistration(config)
  File "/home/lthach/DeepGlobalRegistration/core/deep_global_registration.py", line 82, in __init__
    assert os.path.exists(config.weights)
AssertionError

How can i deal with it?  
Thanks!

**Comment by chrischoy** [comment]
You would need a larger GPU or reduce the batch size.
