### ISSUE TITLE
Possible bug in MinkowskiInterpolation

### ISSUE THREAD

**Issue by qq456cvb** [NVIDIA/MinkowskiEngine#383]
**Describe the bug**

I use ME.MinkowskiInterpolation (v0.5.4) to interpolate intermediate features with provided coordinates. However, sometimes the output feature is transposed and backward through MinkowskiInterpolation gives me an error.

What I figured out is that, when the input coordinates are all zeros, the bug is 100% reproduced.

************************************************************************************
**To Reproduce**
Steps to reproduce the behavior. If the code is not attached and cannot be reproduced easily, the bug report will be closed without any comments.

- a minimally reproducible code.
```
    import MinkowskiEngine as ME
    import torch
    interp = ME.MinkowskiInterpolation()
    
    # create point and features, all with batch 0
    pc = torch.randint(-10, 10, size=(32, 4), dtype=torch.float32, device='cuda')
    pc[:, 0] = 0
    feat = torch.randn(32, 3, dtype=torch.float32, device='cuda', requires_grad=True)
    
    # feature to interpolate
    x = ME.SparseTensor(feat, pc, device='cuda')
    
    # samples with original coordinates, OK for now
    samples = pc
    y = interp(x, samples)
    torch.sum(y).backward()
    print(y.shape, y.stride())
>>> torch.Size([32, 3]) (1, 32)
    
    # samples with all zeros, shape is inconsistent and backward gives error
    samples = torch.zeros_like(pc)
    samples[:, 0] = 0
    y = interp(x, samples)
    torch.sum(y).backward()
    print(y.shape, y.stride())
>>> torch.Size([3, 32]) (32, 1)
>>> Traceback (most recent call last):
  File "/home/neil/report_bug.py", line 29, in <module>
    torch.sum(y).backward()
  File "/home/neil/anaconda3/envs/torch171/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/neil/anaconda3/envs/torch171/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Function MinkowskiInterpolationFunctionBackward returned an invalid gradient at index 0 - got [32, 32] but expected shape compatible with [32, 3]
```

************************************************************************************
**Expected behavior**
```
    import MinkowskiEngine as ME
    import torch
    interp = ME.MinkowskiInterpolation()
    
    # create point and features, all with batch 0
    pc = torch.randint(-10, 10, size=(32, 4), dtype=torch.float32, device='cuda')
    pc[:, 0] = 0
    feat = torch.randn(32, 3, dtype=torch.float32, device='cuda', requires_grad=True)
    
    # feature to interpolate
    x = ME.SparseTensor(feat, pc, device='cuda')
    
    # samples with original coordinates, OK for now
    samples = pc
    y = interp(x, samples)
    torch.sum(y).backward()
    print(y.shape, y.stride())
>>> torch.Size([32, 3]) (1, 32)
    
    # samples with all zeros, shape is inconsistent and backward gives error
    samples = torch.zeros_like(pc)
    samples[:, 0] = 0
    y = interp(x, samples)
    torch.sum(y).backward()
    print(y.shape, y.stride())
>>> torch.Size([32, 3]) (1, 32)
```
and no error in the second backward.

************************************************************************************
**Desktop (please complete the following information):**

 - OS: Ubuntu 16.04
 - Python version: 3.8.5
 - Pytorch version: 1.7.1
 - CUDA version: 10.2
 - NVIDIA Driver version: 440.33.01
 - Minkowski Engine version: 0.5.4
 - Output of the following command. (If you installed the latest MinkowskiEngine, paste the output of `python -c "import MinkowskiEngine as ME; ME.print_diagnostics()"`. Otherwise, paste the output of the following command.)

```
wget -q https://raw.githubusercontent.com/NVIDIA/MinkowskiEngine/master/MinkowskiEngine/diagnostics.py ; python diagnostics.py
```
==========System==========
Linux-4.15.0-142-generic-x86_64-with-glibc2.10
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]
==========Pytorch==========
1.7.1
torch.cuda.is_available(): True
==========NVIDIA-SMI==========
/usr/bin/nvidia-smi
Driver Version 440.33.01
CUDA Version 10.2
VBIOS Version 86.02.39.00.90
Image Version G001.0000.01.04
==========NVCC==========
/usr/local/cuda-10.2/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
==========CC==========
/usr/bin/c++
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

==========MinkowskiEngine==========
/home/neil/anaconda3/envs/torch171/lib/python3.8/site-packages/MinkowskiEngine/__init__.py:36: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
  warnings.warn(
0.5.4
MinkowskiEngine compiled with CUDA Support: True
NVCC version MinkowskiEngine is compiled: 10020
CUDART version MinkowskiEngine is compiled: 10020

**Comment by tau-yihouxiang** [comment]
I am also enchanting the same issue. The returned feature from MinkowskiInterpolation is transposed! This is definitely a bug.

**Comment by chrischoy** [comment]
Thanks for reporting the issue.

There was a problem in the sparse matrix multiplication exception handling when the sparse matrix was zero.
