### ISSUE TITLE
install error in pytorch 1.5.1 cuda 10.3   minkowski0.4.3  

### ISSUE THREAD

**Issue by emilypython** [NVIDIA/MinkowskiEngine#422]
NVCC src/coords_manager.cu
nvcc fatal   : Unsupported gpu architecture 'compute_30'
make: *** [Makefile:167：objs/cuda/coords_manager.o] 错误 1
make: *** 正在等待未完成的任务....
Traceback (most recent call last):
  File "setup.py", line 188, in <module>
    run_command(*compile_args)
  File "setup.py", line 90, in run_command
    subprocess.check_call(args)
  File "/home/msy/anaconda3/envs/sparsem/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-j12', 'PYTHON=/home/msy/anaconda3/envs/sparsem/bin/python', 'BLAS=openblas')' returned non-zero exit status 2
************************************************************************************
**To Reproduce**
Steps to reproduce the behavior. If the code is not attached and cannot be reproduced easily, the bug report will be closed without any comments.

- a minimally reproducible code.

************************************************************************************
**Desktop (please complete the following information):**

 - OS: [e.g. Ubuntu 20.04]
 - Python version: [e.g. 3.7.5]
 - Pytorch version: [e.g. 1.5.1]
 - CUDA version: [e.g. 10.2]
 - NVIDIA Driver version: [e.g. 450.11]
 - Minkowski Engine version [e.g. 0.4.3]
 - Output of the following command. (If you installed the latest MinkowskiEngine, paste the output of `python -c "import MinkowskiEngine as ME; ME.print_diagnostics()"`. Otherwise, paste the output of the following command.)

**Comment by JimmyWong1998** [comment]
Hi, I also met this problem. Have you solved that?

**Comment by serser** [comment]
Commenting out `SM_30` in the Makefile works.

**Comment by serser** [comment]
but met https://github.com/NVIDIA/MinkowskiEngine/issues/177 on cuda11. :(

**Comment by liuxuexun** [comment]
> but met [#177](https://github.com/NVIDIA/MinkowskiEngine/issues/177) on cuda11. :(

Have you solved the problem? Thanks.
