### ISSUE TITLE
ModuleNotFoundError: No module named 'MinkowskiEngineBackend'

### ISSUE THREAD

**Issue by brigr** [NVIDIA/MinkowskiEngine#511]
I compiled MinkowskiEngine versions 0.4.0 and 0.5.4 on Linux with Cuda 11.4, Python 3.6.9 and with uname -a output

Linux [HOSTNAME] 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

For either version, I obtain the following error when I try to import the library

>>> import MinkowskiEngine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/skaravarsamis/sparse-ncnet/MinkowskiEngine/MinkowskiEngine/__init__.py", line 53, in <module>
    from MinkowskiEngineBackend._C import (
ModuleNotFoundError: No module named 'MinkowskiEngineBackend'
>>> 

Is there any known way to correctly bypass this error?

**Comment by LinoComesana** [comment]
I have the same problem when I run `import MinkowskiEngine as ME` within a docker container. I pulled the image from  [https://hub.docker.com/r/uvarc/minkowskiengine/tags](https://hub.docker.com/r/uvarc/minkowskiengine/tags)

**Comment by aprilbian** [comment]
have you resolved this? many thanks in advance

**Comment by m-pabst** [comment]
same for me when using the docker file

**Comment by jodyngo** [comment]
is there anyone resolved this problem?

**Comment by CaesarYD** [comment]
have you resolved this problem?

**Comment by benemer** [comment]
Are you using a virtual environment? In my case, the issue was the `--user` flag when installing the MinkowskiEngine.

I activated my venv and then installed it with `python3 setup.py install --force_cuda --blas=openblas`, which finally worked.

EDIT: Just saw that this issue is quite old, but maybe it still helps someone :)
