### ISSUE TITLE
MinkowskiEngine building wheels

### ISSUE THREAD

**Issue by lamiaa-menshawy** [NVIDIA/MinkowskiEngine#572]
**Describe the bug**

- Please complete all sections of this template if applicable. For installation, you must report the environment. Otherwise, your issue will be closed automatically.

************************************************************************************
**To Reproduce**
Steps to reproduce the behavior. If the code is not attached and cannot be reproduced easily, the bug report will be closed without any comments.

- a minimally reproducible code.

************************************************************************************
**Expected behavior**

************************************************************************************
**Desktop (please complete the following information):**

 - OS: [e.g. Ubuntu 18.04]
 - Python version: [e.g. 3.8.5]
 - Pytorch version: [e.g. 1.7.1]
 - CUDA version: [e.g. 11.1]
 - NVIDIA Driver version: [e.g. 450.11]
 - Minkowski Engine version [e.g. 0.5.0]
 - Output of the following command. (If you installed the latest MinkowskiEngine, paste the output of `python -c "import MinkowskiEngine as ME; ME.print_diagnostics()"`. Otherwise, paste the output of the following command.)

```
wget -q https://raw.githubusercontent.com/NVIDIA/MinkowskiEngine/master/MinkowskiEngine/diagnostics.py ; python diagnostics.py
```

************************************************************************************
**Additional context**

**Comment by lamiaa-menshawy** [comment]
/content/MinkowskiEngine/MinkowskiEngine/MinkowskiEngine Processing /content/MinkowskiEngine/MinkowskiEngine/MinkowskiEngine   Preparing metadata (setup.py) ... done Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (from MinkowskiEngine==0.5.4) (2.1.0+cu121) Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from MinkowskiEngine==0.5.4) (1.23.5) Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch->MinkowskiEngine==0.5.4) (3.13.1) Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch->MinkowskiEngine==0.5.4) (4.5.0) Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch->MinkowskiEngine==0.5.4) (1.12) Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch->MinkowskiEngine==0.5.4) (3.2.1) Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch->MinkowskiEngine==0.5.4) (3.1.2) Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch->MinkowskiEngine==0.5.4) (2023.6.0) Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch->MinkowskiEngine==0.5.4) (2.1.0) Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch->MinkowskiEngine==0.5.4) (2.1.3) Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch->MinkowskiEngine==0.5.4) (1.3.0) Building wheels for collected packages: MinkowskiEngine   error: subprocess-exited-with-error      × python setup.py bdist_wheel did not run successfully.   │ exit code: 1   ╰─> See above for output.      note: This error originates from a subprocess, and is likely not a problem with pip.   Building wheel for MinkowskiEngine (setup.py) ... error   ERROR: Failed building wheel for MinkowskiEngine   Running setup.py clean for MinkowskiEngine Failed to build MinkowskiEngine ERROR: Could not build wheels for MinkowskiEngine, which is required to install pyproject.toml-based projects

**Comment by bring-nirachornkul** [comment]
Same to me. I can't install as well.

Here is my error : 


```
/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/core/jit_type.h(615): error: no operator "=" matches these operands
                  operand types are: c10::optional<__nv_bool> = __nv_bool
      
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/core/jit_type.h(1060): error: no instance of constructor "c10::NamedType::NamedType" matches the argument list
                  argument types are: (c10::TypeKind, c10::QualifiedName)
      
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/core/jit_type.h(1503): error: no instance of overloaded function "c10::TensorType::create" matches the argument list
                  argument types are: (const c10::nullopt_t, const c10::DeviceType, {...}, const c10::nullopt_t)
      
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/core/jit_type.h(1513): error: no suitable constructor exists to convert from "c10::ScalarType" to "c10::optional<c10::ScalarType>"
      
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/core/jit_type.h(1515): error: no suitable constructor exists to convert from "c10::ScalarType" to "c10::optional<c10::ScalarType>"
      
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/core/jit_type.h(1517): error: no suitable constructor exists to convert from "c10::ScalarType" to "c10::optional<c10::ScalarType>"
      
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/core/jit_type.h(1746): error: no instance of constructor "c10::optional<T>::optional [with T=std::string]" matches the argument list
                  argument types are: (std::string)
      
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/core/jit_type.h(1915): error: no suitable constructor exists to convert from "size_t" to "c10::optional<size_t>"
      
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/core/jit_type.h(2021): error: no suitable constructor exists to convert from "size_t" to "c10::optional<size_t>"
      
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/c10/util/TypeList.h(183): error: class "c10::guts::typelist::detail::contains<c10::impl::valid_dict_key_types, c10::IValue, void>" has no member "type"
                detected during:
                  instantiation of type "c10::guts::typelist::contains<c10::impl::valid_dict_key_types, c10::IValue>"
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/core/Dict.h(203): here
                  instantiation of class "c10::Dict<Key, Value> [with Key=c10::IValue, Value=c10::IValue]"
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/core/ivalue_inl.h(416): here
      
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/core/Dict.h(203): error: name followed by "::" must be a class or namespace name
                detected during instantiation of class "c10::Dict<Key, Value> [with Key=c10::IValue, Value=c10::IValue]"
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/core/ivalue_inl.h(416): here
      
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/core/ivalue_inl.h(499): error: no suitable user-defined conversion from "lambda [](c10::ivalue::Future &)->void" to "std::function<void (c10::ivalue::Future &)>" exists
      
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/core/ivalue_inl.h(1492): error: no instance of constructor "std::reference_wrapper<_Tp>::reference_wrapper [with _Tp=const std::string]" matches the argument list
                  argument types are: (const std::string)
      
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/c10/util/Optional.h(1116): error: no instance of constructor "c10::optional<T>::optional [with T=c10::string_view]" matches the argument list
                  argument types are: (c10::string_view)
                detected during instantiation of "c10::optional<std::decay<T>::type> c10::make_optional(T &&) [with T=c10::string_view]"
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/core/operator_name.h(31): here
      
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/Functions.h(471): error: no suitable constructor exists to convert from "c10::MemoryFormat" to "c10::optional<c10::MemoryFormat>"
      
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/Functions.h(473): error: no suitable constructor exists to convert from "c10::MemoryFormat" to "c10::optional<c10::MemoryFormat>"
      
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/Functions.h(536): error: no suitable constructor exists to convert from "int" to "c10::optional<int64_t>"
      
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/c10/util/ArrayRef.h(212): error: class "std::enable_if<<error-constant>, c10::ArrayRef<int64_t>>" has no member "type"
                detected during:
                  instantiation of "c10::ArrayRef<T>::operator= [with T=int64_t]" based on template argument <c10::optional<c10::IntArrayRef> &>
      /usr/include/c++/11/type_traits(1087): here
                  instantiation of class "std::is_assignable<_Tp, _Up> [with _Tp=c10::ArrayRef<int64_t> &, _Up=c10::optional<c10::IntArrayRef> &]"
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/Functions.h(2468): here
      
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/c10/util/Optional.h(585): error: class "std::enable_if<<error-constant>, c10::optional<c10::IntArrayRef> &>" has no member "type"
                detected during instantiation of "c10::optional<T>::operator= [with T=c10::IntArrayRef]" based on template argument <c10::optional<c10::IntArrayRef> &>
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/Functions.h(2468): here
      
      /home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/ATen/Functions.h(2533): error: no suitable user-defined conversion from "c10::IntArrayRef" to "c10::optional<c10::IntArrayRef>" exists
      
      Error limit reached.
      100 errors detected in the compilation of "/tmp/pip-req-build-y03m21d6/src/global_pooling_gpu.cu".
      Compilation terminated.
      [12/21] c++ -MMD -MF /tmp/pip-req-build-y03m21d6/build/temp.linux-x86_64-cpython-38/tmp/pip-req-build-y03m21d6/src/direct_max_pool.o.d -pthread -B /home/blinkdrive/anaconda3/envs/py3-mink/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include -I/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/TH -I/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/include/THC -I/tmp/pip-req-build-y03m21d6/src -I/tmp/pip-req-build-y03m21d6/src/3rdparty -I/home/blinkdrive/anaconda3/envs/py3-mink/include/python3.8 -c -c /tmp/pip-req-build-y03m21d6/src/direct_max_pool.cpp -o /tmp/pip-req-build-y03m21d6/build/temp.linux-x86_64-cpython-38/tmp/pip-req-build-y03m21d6/src/direct_max_pool.o -fopenmp -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
      cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1666, in _run_ninja_build
          subprocess.run(
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '12']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-y03m21d6/setup.py", line 320, in <module>
          setup(
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
          build_ext.build_extensions(self)
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 530, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1355, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/blinkdrive/anaconda3/envs/py3-mink/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for MinkowskiEngine
  Running setup.py clean for MinkowskiEngine
Failed to build MinkowskiEngine
ERROR: Could not build wheels for MinkowskiEngine, which is required to install pyproject.toml-based projects
```
