### ISSUE TITLE
About Running Issues on NVIDIA RTX 4090 Graphics Card

### ISSUE THREAD

**Issue by azhe990510** [NVIDIA/MinkowskiEngine#577]
When using the RTX 4090 graphics card and installing the MinkowskiEngine, we encountered the following error when performing pooling operations such as AvgPooling. However, no such error occurs when using an RTX 3090.

```
 File "/root/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/MinkowskiEngine/MinkowskiPooling.py", line 171, in forward
    outfeat = self.pooling.apply(
  File "/root/anaconda3/lib/python3.9/site-packages/MinkowskiEngine/MinkowskiPooling.py", line 70, in forward
    out_feat, num_nonzero = fw_fn(
RuntimeError: <unknown> at /tmp/pip-install-u79gcb3m/minkowskiengine_c9dccb781db24a2d81cf8b123a030ecd/src/gpu.cu:100
```

Is there any solution available to support the RTX 4090 graphics card?

**Comment by XuyangZhang0223** [comment]
I also encounter this error when using my RTX 4060 graphics card, the error is the same as yours (`MinkowskiEngine/src/gpu.cu:100`) when I set the SparseTensorQuantizationMode to UNWEIGHTED_AVERAGE, but there is no error when it is set to RANDOM_SUBSAMPLE.

Have you find the solution? Thx!

**Comment by ZiliangMiao** [comment]
I also encounter the same error using RTX 4090
RuntimeError: <unknown> at /tmp/pip-req-build-up7naarj/src/gpu.cu:100

**Comment by ZiliangMiao** [comment]
@chrischoy Same problem still unsolved, could you please provide any suggestions? 
RTX4090, python=3.8, pytorch=1.10.0-cu111, pytorch-lightning=1.9.0, MinkowskiEngine=0.5.4
If `quantization_mode=ME.SparseTensorQuantizationMode.UNWEIGHTED_AVERAGE`, it will cause RuntimeError:
```
  File "/home/user/Projects/MosPretrain/scripts/train.py", line 101, in <module>
    main()
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/Projects/MosPretrain/scripts/train.py", line 97, in main
    trainer.fit(model, train_dataloader, val_dataloader, ckpt_path=resume)
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 88, in launch
    return function(*args, **kwargs)
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1103, in _run
    results = self._run_stage()
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1182, in _run_stage
    self._run_train()
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run_train
    self._run_sanity_check()
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1267, in _run_sanity_check
    val_loop.run()
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1485, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 359, in validation_step
    return self.model(*args, **kwargs)
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 110, in forward
    return self._forward_module.validation_step(*inputs, **kwargs)
  File "/home/user/Projects/MosPretrain/src/mos4d/models/nusc_models.py", line 88, in validation_step
    out = self.forward(point_clouds)
  File "/home/user/Projects/MosPretrain/src/mos4d/models/nusc_models.py", line 61, in forward
    out = self.model(past_point_clouds)
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/Projects/MosPretrain/src/mos4d/models/nusc_models.py", line 200, in forward
    sparse_tensor = tensor_field.sparse()
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/MinkowskiTensorField.py", line 354, in sparse
    features = MinkowskiSPMMAverageFunction().apply(
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/sparse_matrix_functions.py", line 183, in forward
    result, COO, vals = spmm_average(
  File "/home/user/anaconda3/envs/4dmos/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/sparse_matrix_functions.py", line 93, in spmm_average
    result, COO, vals = MEB.coo_spmm_average_int32(
RuntimeError: <unknown> at /home/user/Installations/MinkowskiEngine/src/gpu.cu:100
```

**Comment by CorgiBoyG** [comment]
I am also experiencing this problem, is there any way to fix it, thanks.
![Image](https://github.com/user-attachments/assets/f1c17c66-4e98-4ea2-a134-70e25f2e3eb6)

**Comment by ZiliangMiao** [comment]
Upgrade pytorch version >= 1.12 can solve this problem.

**Comment by congwei45** [comment]
> Upgrade pytorch version >= 1.12 can solve this problem.

I also have this problem, but my pytorch version==1.13.0. Do you know how to fix this?
Start training
Traceback (most recent call last):
  File "/data/cw/Experiment/AGILE3D/main.py", line 261, in <module>
    main(args)
  File "/data/cw/Experiment/AGILE3D/main.py", line 189, in main
    train_stats, train_total_iter = train_one_epoch(
  File "/data/cw/Experiment/AGILE3D/engine.py", line 53, in train_one_epoch
    pcd_features, aux, coordinates, pos_encodings_pcd = model.forward_backbone(data, raw_coordinates=raw_coords)
  File "/data/cw/Experiment/AGILE3D/models/agile3d.py", line 173, in forward_backbone
    coords.append(self.pooling(coords[-1]))
  File "/home/cw/anaconda3/envs/agile3d/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cw/anaconda3/envs/agile3d/lib/python3.10/site-packages/MinkowskiEngine/MinkowskiPooling.py", line 171, in forward
    outfeat = self.pooling.apply(
  File "/home/cw/anaconda3/envs/agile3d/lib/python3.10/site-packages/MinkowskiEngine/MinkowskiPooling.py", line 70, in forward
    out_feat, num_nonzero = fw_fn(
RuntimeError: <unknown> at /tmp/pip-req-build-eavlxacw/src/gpu.cu:100
wandb: 🚀 View run dandy-armadillo-300 at: https://wandb.ai/congwei-shenyang-institute-of-automation/AGILE3D/runs/ccemxb5c
wandb: Find logs at: wandb/run-20241128_120602-ccemxb5c/logs

**Comment by han16nah** [comment]
Similar issue here, are there any news on this? .. I'm trying to use [synorim](https://github.com/huangjh-pub/synorim/tree/merged/pytorch)

I have an RTX 4090, Python 3.8.20 and pytorch 1.10.2

```
python evaluate.py configs/mpc-cape/test_pretrained.yaml
/home/hannah/micromamba/envs/synorim/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/__init__.py:36: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
  warnings.warn(
Checkpoint loaded from out_pretrained/cape/basis/best.pth.
Test:   0%|                                                                                            | 0/209 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "evaluate.py", line 87, in <module>
    test_meter = test_epoch()
  File "evaluate.py", line 53, in test_epoch
    test_result, test_metric = net_model.test_step(data, batch_idx)
  File "/home/hannah/projects/synorim/pytorch/models/full_sync.py", line 117, in test_step
    basis_output, desc_output, all_sels = self(batch)
  File "/home/hannah/micromamba/envs/synorim/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hannah/projects/synorim/pytorch/models/full_sync.py", line 30, in forward
    s_basis_desc, s_sels = self.basis_net(batch)
  File "/home/hannah/micromamba/envs/synorim/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hannah/projects/synorim/pytorch/models/basis_net.py", line 70, in forward
    soutput = self.backbone(sinput)
  File "/home/hannah/micromamba/envs/synorim/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hannah/projects/synorim/pytorch/models/spconv.py", line 91, in forward
    out_skip = self.in_norms[layer_id](out_skip)
  File "/home/hannah/micromamba/envs/synorim/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hannah/micromamba/envs/synorim/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/MinkowskiNormalization.py", line 390, in forward
    output = self.inst_norm.apply(
  File "/home/hannah/micromamba/envs/synorim/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/MinkowskiNormalization.py", line 210, in forward
    mean, num_nonzero = gpool_avg_forward(
RuntimeError: <unknown> at /home/hannah/projects/synorim/MinkowskiEngine/src/gpu.cu:100
> /home/hannah/micromamba/envs/synorim/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/MinkowskiNormalization.py(210)forward()
-> mean, num_nonzero = gpool_avg_forward(
```

**Comment by solemotive** [comment]
## My configuration：
ubuntu20.04
4060
CUDA11.1（NVCC -V）
pytorch1.9.0(or1.10.0)  cu11.1
##  The following error was encountered when running the demo.py:
``` 
Traceback (most recent call last):
  File "/opt/project/regtr/src/demo.py", line 196, in <module>
    main()
  File "/opt/project/regtr/src/demo.py", line 182, in main
    outputs = model(data_batch)
  File "/opt/conda/envs/regtr_pytorch1.10.0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/project/regtr/src/models/regtr.py", line 117, in forward
    kpconv_meta = self.preprocessor(batch['src_xyz'] + batch['tgt_xyz'])
  File "/opt/conda/envs/regtr_pytorch1.10.0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/project/regtr/src/models/backbone_kpconv/kpconv.py", line 489, in forward
    pool_p, pool_b = batch_grid_subsampling_kpconv_gpu(
  File "/opt/project/regtr/src/models/backbone_kpconv/kpconv.py", line 232, in batch_grid_subsampling_kpconv_gpu
    sparse_tensor = ME.SparseTensor(
  File "/opt/conda/envs/regtr_pytorch1.10.0/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py", line 271, in __init__
    coordinates, features, coordinate_map_key = self.initialize_coordinates(
  File "/opt/conda/envs/regtr_pytorch1.10.0/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/MinkowskiSparseTensor.py", line 334, in initialize_coordinates
    features = spmm_avg.apply(self.inverse_mapping, cols, size, features)
  File "/opt/conda/envs/regtr_pytorch1.10.0/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/sparse_matrix_functions.py", line 183, in forward
    result, COO, vals = spmm_average(
  File "/opt/conda/envs/regtr_pytorch1.10.0/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/sparse_matrix_functions.py", line 93, in spmm_average
    result, COO, vals = MEB.coo_spmm_average_int32(
RuntimeError: <unknown> at /opt/project/MinkowskiEngine-0.5.4.1/src/gpu.cu:100
``` 
## Can anyone help me solve it？

**Comment by rstonghua** [comment]
I have met the same error, when I running ME on RTX4090.
**My configuration:**
ubuntu20.04
4060
CUDA11.1（NVCC -V）
pytorch1.9.0 cu11.1
**The Traceback is as follow:**
`Traceback (most recent call last):
  File "/home/fcy/TSP3D-main/train_dist_mod.py", line 342, in <module>
    ckpt_path = train_tester.main(opt)
  File "/home/fcy/TSP3D-main/main_utils.py", line 381, in main
    self.train_one_epoch(
  File "/home/fcy/TSP3D-main/main_utils.py", line 514, in train_one_epoch
    losses = model(inputs, gt_bboxes_3d, gt_labels_3d, gt_all_bbox_new, auxi_bbox, img_metas, epoch)
  File "/home/fcy/miniconda3/envs/TSP3D/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fcy/miniconda3/envs/TSP3D/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/fcy/miniconda3/envs/TSP3D/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fcy/TSP3D-main/models/bdetr.py", line 118, in forward
    losses = self.head.forward_train(x,text_feats, text_attention_mask, gt_bboxes, gt_labels, gt_all_bbox_new, auxi_bbox, img_metas)
  File "/home/fcy/TSP3D-main/models/multilevel_head.py", line 670, in forward_train
    self(x, text_feats, text_attention_mask, gt_bboxes, gt_labels, gt_all_bbox_new, auxi_bbox, img_metas,pc)
  File "/home/fcy/miniconda3/envs/TSP3D/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fcy/TSP3D-main/models/multilevel_head.py", line 257, in forward
    x_level_features = inputs[i].features_at_coordinates(coords)  # select for partial addition
  File "/home/fcy/miniconda3/envs/TSP3D/lib/python3.9/site-packages/MinkowskiEngine/MinkowskiSparseTensor.py", line 713, in features_at_coordinates
    return MinkowskiInterpolationFunction().apply(
  File "/home/fcy/miniconda3/envs/TSP3D/lib/python3.9/site-packages/MinkowskiEngine/MinkowskiInterpolation.py", line 52, in forward
    out_feat, in_map, out_map, weights = fw_fn(
RuntimeError: <unknown> at /home/fcy/TSP3D-main/MinkowskiEngine/src/gpu.cu:100`

**Comment by rstonghua** [comment]
> Upgrade pytorch version >= 1.12 can solve this problem.

Besides upgrading the pytorch version, do I need to update cuda version to 11.3. I find cuda11.1 doesn't support pytorch1.12.
