### ISSUE TITLE
Compile Test Failed

### ISSUE THREAD

**Issue by HaFred** [NVIDIA/MinkowskiEngine#592]
**I have gcc 9 installed for cuda 11, but failed while running tests/cpp/setup.py.** Any help will be appreciated thanks!
```
(base) root:~/MinkowskiEngine/tests/cpp$ python setup.py install --test=coordinate_map_cpu
running install
~/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
~/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing MinkowskiEngineTest.egg-info/PKG-INFO
writing dependency_links to MinkowskiEngineTest.egg-info/dependency_links.txt
writing top-level names to MinkowskiEngineTest.egg-info/top_level.txt
reading manifest file 'MinkowskiEngineTest.egg-info/SOURCES.txt'
writing manifest file 'MinkowskiEngineTest.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'MinkowskiEngineTest._C' extension
Emitting ninja build file ~/MinkowskiEngine/tests/cpp/build/temp.linux-x86_64-3.8/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] gcc -MMD -MF ~/MinkowskiEngine/tests/cpp/build/temp.linux-x86_64-3.8~/MinkowskiEngine/tests/cpp/coordinate_map_cpu_test.o.d -pthread -B ~/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I~/lib/python3.8/site-packages/torch/include -I~/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I~/lib/python3.8/site-packages/torch/include/TH -I~/lib/python3.8/site-packages/torch/include/THC -I~/MinkowskiEngine/src -I~/MinkowskiEngine/src/3rdparty -I/usr/local/cuda-11.3/include -I~/include/python3.8 -c -c ~/MinkowskiEngine/tests/cpp/coordinate_map_cpu_test.cpp -o ~/MinkowskiEngine/tests/cpp/build/temp.linux-x86_64-3.8~/MinkowskiEngine/tests/cpp/coordinate_map_cpu_test.o -fopenmp -g -DDEBUG -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from ~/MinkowskiEngine/src/allocators.cuh:39,
                 from ~/MinkowskiEngine/src/kernel_region.hpp:40,
                 from ~/MinkowskiEngine/src/coordinate_map.hpp:30,
                 from ~/MinkowskiEngine/src/coordinate_map_cpu.hpp:28,
                 from ~/MinkowskiEngine/tests/cpp/coordinate_map_cpu_test.cpp:26:
~/MinkowskiEngine/src/gpu.cuh:149: warning: "THRUST_CHECK" redefined
  149 | #define THRUST_CHECK(condition)                                                \
      | 
In file included from ~/MinkowskiEngine/src/coordinate.hpp:30,
                 from ~/MinkowskiEngine/src/coordinate_map.hpp:29,
                 from ~/MinkowskiEngine/src/coordinate_map_cpu.hpp:28,
                 from ~/MinkowskiEngine/tests/cpp/coordinate_map_cpu_test.cpp:26:
~/MinkowskiEngine/src/utils.hpp:169: note: this is the location of the previous definition
  169 | #define THRUST_CHECK(condition) condition;
      | 
gcc -pthread -shared -B ~/compiler_compat -L~/lib -Wl,-rpath=~/lib -Wl,--no-as-needed -Wl,--sysroot=/ ~/MinkowskiEngine/tests/cpp/build/temp.linux-x86_64-3.8~/MinkowskiEngine/tests/cpp/coordinate_map_cpu_test.o -L~/lib/python3.8/site-packages/torch/lib -lopenblas -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-3.8/MinkowskiEngineTest/_C.cpython-38-x86_64-linux-gnu.so
building 'torch_test_cpp_extension.cuda' extension
Emitting ninja build file ~/MinkowskiEngine/tests/cpp/build/temp.linux-x86_64-3.8/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: error: '~/MinkowskiEngine/tests/cpp/cuda_extension.cpp', needed by '~/MinkowskiEngine/tests/cpp/build/temp.linux-x86_64-3.8/cuda_extension.o', missing and no known rule to make it
Traceback (most recent call last):
  File "~/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1740, in _run_ninja_build
    subprocess.run(
  File "~/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 143, in <module>
    setup(
  File "~/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "~/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "~/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "~/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "~/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "~/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "~/lib/python3.8/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "~/lib/python3.8/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "~/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "~/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "~/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "~/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "~/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "~/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "~/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "~/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "~/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "~/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "~/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "~/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "~/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "~/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "~/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "~/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
    build_ext.build_extensions(self)
  File "~/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "~/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "~/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "~/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "~/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 562, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "~/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1419, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "~/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```
************************************************************************************
**Desktop (please complete the following information):**

==========System==========
Linux-5.11.0-43-generic-x86_64-with-glibc2.17
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
3.8.13 (default, Mar 28 2022, 11:38:47) 
[GCC 7.5.0]
==========Pytorch==========
1.11.0
torch.cuda.is_available(): True
==========NVIDIA-SMI==========
/usr/bin/nvidia-smi
Driver Version 470.86
CUDA Version 11.4
VBIOS Version 94.02.42.00.A9
Image Version G001.0000.03.03
GSP Firmware Version N/A
==========NVCC==========
/usr/local/cuda-11.3/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:15:46_PDT_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0
==========CC==========
CC=gcc
/usr/bin/gcc
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

==========MinkowskiEngine==========
0.5.4
MinkowskiEngine compiled with CUDA Support: True
NVCC version MinkowskiEngine is compiled: 11030
CUDART version MinkowskiEngine is compiled: 11030

**Comment by CiSong10** [comment]
Same issue.  This works for me: https://github.com/NVlabs/instant-ngp/issues/119#issuecomment-1034701258
