### ISSUE TITLE
Issues encountered during local installation

### ISSUE THREAD

**Issue by king1111sadjfoisja** [NVIDIA/MinkowskiEngine#602]
Dear author:

When installing MinkowskiEngine locally, I encountered the following issues:

After executing this command：
`python setup.py install --blas_include_dirs=${CONDA_PREFIX}/include --blas=openblas`
Here is the error message encountered:
```
(gaussian_splatting) (base) gdut403@gdut403-X299-WU8:~/HK/semantic-gaussians-main/MinkowskiEngine$ python setup.py install --blas_include_dirs=${CONDA_PREFIX}/include --blas=openblas
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.8'
WARNING: Skipping MinkowskiEngine as it is not installed.
setup.py:130: UserWarning: torch.cuda.is_available() is False. MinkowskiEngine will compile with CPU_ONLY. Please use `--force_cuda` to compile with CUDA.
  "torch.cuda.is_available() is False. MinkowskiEngine will compile with CPU_ONLY. Please use `--force_cuda` to compile with CUDA."
--------------------------------
| WARNING: CPU_ONLY build set  |
--------------------------------

Using BLAS=openblas
Using the default compiler
running install
/home/gdut403/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/gdut403/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing MinkowskiEngine.egg-info/PKG-INFO
writing dependency_links to MinkowskiEngine.egg-info/dependency_links.txt
writing requirements to MinkowskiEngine.egg-info/requires.txt
writing top-level names to MinkowskiEngine.egg-info/top_level.txt
reading manifest file 'MinkowskiEngine.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'MinkowskiEngine.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-cpython-37
creating build/lib.linux-x86_64-cpython-37/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiCoordinateManager.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine
copying ./MinkowskiEngine/sparse_matrix_functions.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine
copying ./MinkowskiEngine/diagnostics.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiTensorField.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiKernelGenerator.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiPooling.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiNetwork.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiNonlinearity.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiUnion.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiTensor.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiFunctional.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine
copying ./MinkowskiEngine/__init__.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiChannelwiseConvolution.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiConvolution.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiNormalization.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiCommon.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiInterpolation.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiSparseTensor.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiBroadcast.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiPruning.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiOps.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine
creating build/lib.linux-x86_64-cpython-37/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/quantization.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/collation.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/init.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/__init__.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/coords.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/gradcheck.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/summary.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine/utils
creating build/lib.linux-x86_64-cpython-37/MinkowskiEngine/modules
copying ./MinkowskiEngine/modules/senet_block.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine/modules
copying ./MinkowskiEngine/modules/__init__.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine/modules
copying ./MinkowskiEngine/modules/resnet_block.py -> build/lib.linux-x86_64-cpython-37/MinkowskiEngine/modules
running build_ext
building 'MinkowskiEngineBackend._C' extension
creating /home/gdut403/HK/semantic-gaussians-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-37
creating /home/gdut403/HK/semantic-gaussians-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-37/home
creating /home/gdut403/HK/semantic-gaussians-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-37/home/gdut403
creating /home/gdut403/HK/semantic-gaussians-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-37/home/gdut403/HK
creating /home/gdut403/HK/semantic-gaussians-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-37/home/gdut403/HK/semantic-gaussians-main
creating /home/gdut403/HK/semantic-gaussians-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-37/home/gdut403/HK/semantic-gaussians-main/MinkowskiEngine
creating /home/gdut403/HK/semantic-gaussians-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-37/home/gdut403/HK/semantic-gaussians-main/MinkowskiEngine/src
creating /home/gdut403/HK/semantic-gaussians-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-37/pybind
/home/gdut403/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py:330: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Emitting ninja build file /home/gdut403/HK/semantic-gaussians-main/MinkowskiEngine/build/temp.linux-x86_64-cpython-37/build.ninja...
Compiling objects...
```
Omitted some part：
```
File "/home/gdut403/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 600, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/gdut403/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1497, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/gdut403/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1829, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```
It seems like the installation is not successful.I hope you can provide assistance.

**Comment by Xin200203** [comment]
same error :)

**Comment by guanshantingbai** [comment]
same error 😭

**Comment by kohjakob** [comment]
I ran into a similar issue:

`(project-env) user@hostname:~/MinkowskiEngine$ python setup.py install --blas_include_dirs=${CONDA_PREFIX}/include --blas=openblas
WARNING: Skipping MinkowskiEngine as it is not installed.
--------------------------------
| CUDA compilation set         |
--------------------------------

Using BLAS=openblas
Using g++-11 for c++ compilation
running install
/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:79: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:79: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing MinkowskiEngine.egg-info/PKG-INFO
writing dependency_links to MinkowskiEngine.egg-info/dependency_links.txt
writing requirements to MinkowskiEngine.egg-info/requires.txt
writing top-level names to MinkowskiEngine.egg-info/top_level.txt
reading manifest file 'MinkowskiEngine.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'MinkowskiEngine.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying MinkowskiEngine/__init__.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying MinkowskiEngine/MinkowskiChannelwiseConvolution.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying MinkowskiEngine/diagnostics.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying MinkowskiEngine/MinkowskiUnion.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying MinkowskiEngine/MinkowskiNormalization.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying MinkowskiEngine/sparse_matrix_functions.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying MinkowskiEngine/MinkowskiPruning.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying MinkowskiEngine/MinkowskiConvolution.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying MinkowskiEngine/MinkowskiCommon.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying MinkowskiEngine/MinkowskiOps.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying MinkowskiEngine/MinkowskiNetwork.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying MinkowskiEngine/MinkowskiTensor.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying MinkowskiEngine/MinkowskiPooling.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying MinkowskiEngine/MinkowskiInterpolation.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying MinkowskiEngine/MinkowskiBroadcast.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying MinkowskiEngine/MinkowskiFunctional.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying MinkowskiEngine/MinkowskiTensorField.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying MinkowskiEngine/MinkowskiKernelGenerator.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying MinkowskiEngine/MinkowskiSparseTensor.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying MinkowskiEngine/MinkowskiCoordinateManager.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
copying MinkowskiEngine/MinkowskiNonlinearity.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine
creating build/lib.linux-x86_64-cpython-310/MinkowskiEngine/utils
copying MinkowskiEngine/utils/__init__.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine/utils
copying MinkowskiEngine/utils/summary.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine/utils
copying MinkowskiEngine/utils/gradcheck.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine/utils
copying MinkowskiEngine/utils/collation.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine/utils
copying MinkowskiEngine/utils/coords.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine/utils
copying MinkowskiEngine/utils/init.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine/utils
copying MinkowskiEngine/utils/quantization.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine/utils
creating build/lib.linux-x86_64-cpython-310/MinkowskiEngine/modules
copying MinkowskiEngine/modules/__init__.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine/modules
copying MinkowskiEngine/modules/senet_block.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine/modules
copying MinkowskiEngine/modules/resnet_block.py -> build/lib.linux-x86_64-cpython-310/MinkowskiEngine/modules
running build_ext
building 'MinkowskiEngineBackend._C' extension
creating /usr/people/user/MinkowskiEngine/build/temp.linux-x86_64-cpython-310/usr/people/user/MinkowskiEngine/src
creating /usr/people/user/MinkowskiEngine/build/temp.linux-x86_64-cpython-310/pybind
Emitting ninja build file /usr/people/user/MinkowskiEngine/build/temp.linux-x86_64-cpython-310/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: option '--v' is ambiguous; possibilities: '--version' '--verbose'
usage: ninja [options] [targets...]

if targets are unspecified, builds the 'default' target (see manual).

options:
  --version      print ninja version ("1.11.1.git.kitware.jobserver-1")
  -v, --verbose  show all command lines while building
  --quiet        don't show progress status, just command output

  -C DIR   change to DIR before doing anything else
  -f FILE  specify input build file [default=build.ninja]

  -j N     run N jobs in parallel (0 means infinity) [default=10 on this system]
  -k N     keep going until N jobs fail (0 means infinity) [default=1]
  -l N     do not start new jobs if the load average is greater than N
  -n       dry run (don't run commands but act like they succeeded)

  -d MODE  enable debugging (use '-d list' to list modes)
  -t TOOL  run a subtool (use '-t list' to list subtools)
    terminates toplevel options; further flags are passed to the tool
  -w FLAG  adjust warnings (use '-w list' to list warnings)
Traceback (most recent call last):
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
    subprocess.run(
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '--v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/people/user/MinkowskiEngine/setup.py", line 320, in <module>
    setup(
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 186, in setup
    return run_commands(dist)
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 202, in run_commands
    dist.run_commands()
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 983, in run_commands
    self.run_command(cmd)
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/dist.py", line 999, in run_command
    super().run_command(command)
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 1002, in run_command
    cmd_obj.run()
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/command/install.py", line 109, in run
    self.do_egg_install()
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/command/install.py", line 167, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 339, in run_command
    self.distribution.run_command(command)
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/dist.py", line 999, in run_command
    super().run_command(command)
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 1002, in run_command
    cmd_obj.run()
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 177, in run
    cmd = self.call_command('install_lib', warn_dir=False)
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 163, in call_command
    self.run_command(cmdname)
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 339, in run_command
    self.distribution.run_command(command)
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/dist.py", line 999, in run_command
    super().run_command(command)
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 1002, in run_command
    cmd_obj.run()
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/command/install_lib.py", line 19, in run
    self.build()
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/_distutils/command/install_lib.py", line 110, in build
    self.run_command('build_ext')
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 339, in run_command
    self.distribution.run_command(command)
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/dist.py", line 999, in run_command
    super().run_command(command)
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 1002, in run_command
    cmd_obj.run()
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 99, in run
    _build_ext.run(self)
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 365, in run
    self.build_extensions()
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 481, in build_extensions
    self._build_extensions_serial()
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 507, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 264, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 562, in build_extension
    objects = self.compiler.compile(
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1573, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/usr/people/user/miniconda3/envs/project-env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension`

For me it worked with gcc-9, g++-9 and ninja=1.11.1.3:
`export CC=gcc-9
export CXX=g++-9
pip install ninja==1.11.1.3`

Environment:
Ubuntu 22.04.5 LTS
Torch 1.13.1
Cuda Toolkit 11.6

**Comment by MGupta28** [comment]
Hey, were you able to resolve this issue?
