### ISSUE TITLE
No module named 'distutils.msvccompiler'

### ISSUE THREAD

**Issue by Rickilous** [NVIDIA/MinkowskiEngine#605]
**Describe the bug**

(GGSD) xzy@xzy-HP-Z4-G4-Workstation:/data1/jy/code/MinkowskiEngine$ python setup.py install --install-option="--force_cuda" --install-option="--blas=openblas"
WARNING: Skipping MinkowskiEngine as it is not installed.
--------------------------------
| CUDA compilation set         |
--------------------------------
Traceback (most recent call last):
  File "setup.py", line 201, in <module>
    import numpy.distutils.system_info as sysinfo
  File "/home/xzy/anaconda3/envs/GGSD/lib/python3.8/site-packages/numpy/distutils/system_info.py", line 196, in <module>
    from numpy.distutils.command.config import config as cmd_config
  File "/home/xzy/anaconda3/envs/GGSD/lib/python3.8/site-packages/numpy/distutils/command/config.py", line 19, in <module>
    from numpy.distutils.mingw32ccompiler import generate_manifest
  File "/home/xzy/anaconda3/envs/GGSD/lib/python3.8/site-packages/numpy/distutils/mingw32ccompiler.py", line 28, in <module>
    from distutils.msvccompiler import get_build_version as get_build_msvc_version
ModuleNotFoundError: No module named 'distutils.msvccompiler'

************************************************************************************
**To Reproduce**

Whether I install Minkowski Engine through pip or locally, the above bugs will occur.

************************************************************************************
**Desktop (please complete the following information):**

 - OS: [Ubuntu 22.04.2 LTS]
 - Python version: [Python 3.8.19]
 - Pytorch version: [2.0.1]
 - CUDA version: [11.7]
 - NVIDIA Driver version: [550.107.02]
 - Minkowski Engine version :[Installation failed]

************************************************************************************
**Additional context**
My attempt:
I tried to use Setup tools to bypass the issue of missing distutls, but it seems that there is still a problem.
(GGSD)  xzy@xzy-HP-Z4-G4-Workstation :/data1/jy/code/MinkowskiEngine$ python -c "import distutils; print(distutils.__ file__)"
/home/xzy/anaconda3/envs/GGSD/lib/python3.8/site-packages/setuptools/_distutils/__init__.py
(GGSD)  xzy@xzy-HP-Z4-G4-Workstation :/data1/jy/code/MinkowskiEngine$ pip list| grep setuptools
setuptools                    75.1.0
WARNING: There was an error checking the latest version of pip.
(GGSD)  xzy@xzy-HP-Z4-G4-Workstation :/data1/jy/code/MinkowskiEngine$ pip list| grep distutils
WARNING: There was an error checking the latest version of pip.

**Comment by Yangl1nFeng** [comment]
Have you resolved it? I encountered the same issue!

**Comment by Rickilous** [comment]
> Have you resolved it? I encountered the same issue!

No, still working on it.

**Comment by Rickilous** [comment]
> Have you resolved it? I encountered the same issue!

Hey, hello. You can try using Docker to install or downgrade the Python version to 3.7. Both methods are effective for me. (*￣︶￣)

**Comment by Yangl1nFeng** [comment]
> > 你解决了吗？我也遇到了同样的问题！
> 
> 嗨，你好。你可以尝试使用 Docker 安装或降级 Python 版本到 3.7。这两种方法对我来说都很有效。(*￣︶￣)

Thanks, I'll try it!

**Comment by destroy314** [comment]
See https://github.com/numpy/numpy/issues/27405

**Comment by esener1** [comment]
> > Have you resolved it? I encountered the same issue!
> 
> Hey, hello. You can try using Docker to install or downgrade the Python version to 3.7. Both methods are effective for me. (*￣︶￣)

Hey I would be glad if you could share the dockerfile that you used for the installation ? I am having the same error with same desktop versions.

**Comment by ZEROICEWANG** [comment]
change setuptools to 69.5.1 could fix this

**Comment by zhangtlqy** [comment]
> change setuptools to 69.5.1 could fix this将 setuptools 更改为 69.5.1 可以解决此问题

This method is useful. Thanks!
